apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-Deployment
  namespace: default

spec:
  replicas: 3

  selector:
    matchLabels:
      app: movie-frontend

  template:
    metadata:
      labels:
        app: movie-frontend

    spec:
      containers:
      - name: frontend-container
        image: nginx:latest

        ports:
        - containerPort: 80