apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
      - name: backend
        image: monicacontainerregistry123.azurecr.io/movie-backend:1.0
        ports:
        - containerPort: 5000